#!/bin/bash
# simple system update script

if [ "$EUID" -ne 0 ]; then echo "Please run as root"; exit 1; fi

echo ">>> Sync portage tree ..."
ego sync

for d in /var/git/overlay/*/ ; do
	if [ -d "$d/.git" ] ; then
		cd "$d"
		#git config pull.rebase true
		echo ">>> Sync overlay $d ..."
		git pull
	fi 
done

echo ">>> Update eix database ..."
eix-update
