#!/bin/bash
# vim: ts=4 sw=4 et
# simple script to extend the disksize of this box

if [ "$EUID" -ne 0 ]; then echo "Please run as root"; exit 1; fi

echo ">>> Current disk partition layout:"
fdisk -l || true

echo ">>> Resizing disk ..."
growpart /dev/sda 4 || true
resize2fs /dev/sda4 || true

echo ">>> Resize result:"
fdisk -l || true

echo
echo "Done. Please consider rebooting."
