#!/bin/bash
# simple system update script

if [ "$EUID" -ne 0 ]; then echo "Please run as root"; exit 1; fi

if [ ! -d "/var/git/meta-repo" ]; then
  /usr/local/sbin/foo-sync
fi

emerge -avtuDN --with-bdeps=y @world

if [ $? -ne 0 ]; then
  echo "Failure during update: user cancelled or an error ocurred. Please run 'foo-sync' and try again." >&2
  exit 1
fi

echo ">>> Remove obsolete packages ..."
emerge --quiet --depclean

echo ">>> Rebuild preserved packages ..."
emerge -vt @preserved-rebuild
