#!/bin/bash
# simple script to prepare this box to compact the hdd image (zerofree)

echo ">>> Switching runlevel, trying to kill all daemons ..."
telinit 1

echo ">>> Ensure 'rsyslog' is stopped ..."
/etc/init.d/rsynclog stop || echo "Failed to stop service 'rsynclog'."

echo ">>> Ensure 'dhcpd' is stopped ..."
/etc/init.d/dhcpd stop || echo "Failed to stop service 'dhcpd'."

echo ">>> Claim remaining free space by file ..."
sudo bash -c 'dd if=/dev/zero of=/EMPTY bs=1M 2>/dev/null' || true
sudo rm -f /EMPTY

echo ">>> Sync I/O ..."
sync

echo ">>> Mounting root filesystem 'read-only' ..."
mount -o remount,ro /dev/sda4 || echo "Unable to mount in read-only mode. Aborting."; exit 1

echo ">>> Zerofree root filesystem ..."
zerofree -v /dev/sda4

echo "Your system is prepared for compaction. Power off in 5 secs."
shutdown -h -t 5 now "System ready for compaction." 
