#!/bin/bash
# vim: ts=4 sw=4 et
# simple system update script

if [ "$EUID" -ne 0 ]; then echo "Please run as root"; exit 1; fi

# TODO extra features: evaluate cmd arguments => quick (w/o extras), full (with extras)

if [ ! -d "/var/git/meta-repo" ]; then
  /usr/local/sbin/foo-sync
fi

emerge -avtuDN --with-bdeps=y --complete-graph=y @world

if [ $? -ne 0 ]; then
  echo "Failure during update: user cancelled or an error ocurred. Please run 'foo-sync' and try again." >&2
  exit $?
fi

# extra options: comment-in to disable

echo ">>> Rebuilding preserved packages ..."
emerge -vt @preserved-rebuild

echo ">>> Remove obsolete packages ..."
emerge --depclean

echo ">>> Rebuilding preserved packages ..."
emerge -vt @preserved-rebuild

echo ">>> Checking reverse package dependencies ..."
revdep-rebuild
